name: @name@
main: fr.grimtown.RaidToDragon.plugin.RaidPlugin
version: @version@
api-version: @apiVersion@
description: 'Plugin for a short event of GrimTown to wait until the main event'
depend:
  - GlowAPI
  - Citizens
author: GrimTown
authors:
  - BakaAless (Aless#6161)
libraries:
  - org.mongodb:mongodb-driver-sync:4.4.0
  - dev.morphia.morphia:morphia-core:2.2.3
commands:
  raidtodragon:
    aliases:
      - rtd
      - todragon
      - grimtownraidtodragon
      - grimtownrdt
